backend:
  name: git-gateway
  branch: master

# Location where files will be stored in the repo.
media_folder: "src/assets/images"

# The src attribute for uploaded media.
public_folder: "src/assets/images"
